### ISSUE TITLE
Добавить файл urls.py в приложение pawnshop

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#10]
**Что нужно сделать:**
Добавить `urls.py` в приложение pawnshop

**Как это сделать:**
1. Создать файл `urls.py` в приложении `pawnshop`
2. Добавить строку `app_name = 'pawnshop'`
3. Добавить строку `urlpatterns = []`
4. Добавить в urlpatterns в `urls.py` корневого приложения строку `path('/', include('pawnshop.urls', namespace='pawnshop'))`
**Зачем это нужно:**
Для масштабируемости и удобства при написании кода

**Критерии приемки:**
Роут `/` должен вести на приложение `pawnshop`

**Comment by Akram89** [comment]
Выполнено
