### ISSUE TITLE
Написать логику по заполнению модели Operation

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#109]
**Что нужно сделать:**
Написать логику по заполнению модели Operation

**Зачем это нужно:**
Для отслеживания всех операций со стороны кассиров/админов по отношению к займам.

**Критерии приемки:**
При оперециях по добавлению выкупу займов , таблица Operation, автоматически заполняется информацией.  

**Планируемое время работы:**
4 час

Затраченное время:
2 часа

**Comment by qwanysh** [comment]
Реализовано полностью
