### ISSUE TITLE
Авторизация пользователя

### ISSUE THREAD

**Issue by Akram89** [glokzs/lombard_crm#11]
Что нужно сделать: Создать пользователя "суперадмин" с правами и возможностью приглашения других пользователей зарегестрироваться в системе

Как это сделать: 
1. Создать `urls.py` `localhost:8000/accounts/login`
2. Добавить `UserLoginView`. После авторизации редиректить на `localhost:8000/credits/`
3. Создать папку `templates` в приложение `accounts`
4. Добавить папку `user` в папку `templates`
5. Создать `login.html` в папке `templates/user`
6. В `partials/_header.html` установить ссылку на страницу авторизации
7. Показывать кнопку авторизации только для неавторизованных пользователей 

Зачем это нужно: 
Для авторизации на сайте

Критерии приемки: Можно будет создать пользователя через админку и авторизоваться через него. После авторизации кнопка авторизоваться должна пропасть

Планируемое время работы:
2 часа

Затраченное время;
3 часа

**Comment by apollo64** [comment]
Методы  login, logout, register, mail send , html

**Comment by Akram89** [comment]
выполнено
