### ISSUE TITLE
Создать страницу журнала операций

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#117]
Что нужно сделать:

1. Проанализировать журнал операций в smartlombard,
2. Сделать журнал операций

Зачем это нужно:
Для отслеживания всех операций со стороны кассиров/админов по отношению к займам.

Критерии приемки:
Должна содержать поля позволяющие установить кто, что сделал в отношений чего и когда.

Планируемое время работы:
2 часа

Затраченное время:
2 часа

**Comment by qwanysh** [comment]
Реализовано полностью
