### ISSUE TITLE
Настройка и подключение TRAVIS CI

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#124]
Что нужно сделать:
Подключить travis к github

Зачем это нужно:
организация автотестирования загружаемого кода

Критерии приемки:
Тесты проводит тревис автоматически 

Планируемое время работы:
2 час

Затраченное время:

**Comment by qwanysh** [comment]
Тикет мигрирован в тикет #127

**Comment by apollo64** [comment]
Переименован в №127.
