### ISSUE TITLE
Сделать поиск клиентов регистронезависимым

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#13]
**Что нужно сделать:**
Сделать поиск клиентов регистронезависимым
**Как это сделать:**
Изменить `Q` выражения в ClientListAjaxView в `views.py` приложения `pawnshop`
**Зачем это нужно:**
Чтобы легче найти нужного пользователя
**Критерии приемки:**
Поиск должен находить пользователя, даже если пользователь ввел запрос разными регистрами
**Планируемое время работы:**

**Comment by Akram89** [comment]
Выполнено
