### ISSUE TITLE
Узнать у заказчика, по каким полям нужно вести поиск клиента

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#14]
**Что нужно сделать:**
Узнать у заказчика, по каким полям нужно вести поиск клиента
**Как это сделать:**
1. Спросить у заказчика, по каким полям им хотелось бы вести поиск
2. Создать `wiki` с названием 'Поля поиска клиента'
**Зачем это нужно:**
Для удобного поиска клиента
**Критерии приемки:**
Должен создаться `wiki` со списком полей для поиска клиента 
**Планируемое время работы:**

**Comment by Akram89** [comment]
Выполнено
