### ISSUE TITLE
Передавать client_pk через url

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#15]
**Что нужно сделать:**
Сделать так, чтобы после создания клиента `client_pk` передавался в url, а не параметром
**Как это сделать:**
1. Изменить url `path('credits/confirm_document_create/', ConfirmDocumentCreateView.as_view(), name='confirm_document_create'),` на `path('clients/<int:client_pk>/confirm_document_create/', ConfirmDocumentCreateView.as_view(), name='confirm_document_create'),`
2. Изменить `get_success_url` в `ClientCreateView`, чтобы он вел на новый url
3. Изменить `form_valid` в `ConfirmDocumentCreateView`, чтобы он брал `client_pk` из url

**Зачем это нужно:**
Чтобы удалить скрытый input из формы добавления подтверждающего документа
**Критерии приемки:**
Url добавления подтверждающего документа должен содержать `client_pk`
**Планируемое время работы:**
5 минут

**Comment by Akram89** [comment]
Выполнено
