### ISSUE TITLE
Стилизовать форму добавления клиентов

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#16]
**Что нужно сделать:**
Стилизовать форму `ClientForm`

**Как это сделать:**
1. В `forms.py` каждому полю добавить класс `(form-control-file` для файловых полей, `form-control` для остальных) 

**Зачем это нужно:**
Для улучшения внешнего вида

**Критерии приемки:**
Стили Bootstrap должны затронуть форму добавления клиентов

**Планируемое время работы:**
5 минут

**Затраченное время:**
02:04 - 02:18

**Comment by Akram89** [comment]
выполнено
