### ISSUE TITLE
Стилизовать форму добавления подтверждающего документа

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#17]
**Что нужно сделать:**
Стилизовать форму `ConfirmDocumentForm`

**Как это сделать:**
1. В `forms.py` каждому полю добавить класс `(form-control-file` для файловых полей, `form-control` для остальных) 

**Зачем это нужно:**
Для улучшения внешнего вида

**Критерии приемки:**
Стили Bootstrap должны затронуть форму добавления подтверждающего документа

**Планируемое время работы:**
10 минут

**Затраченное время:**
02:40 - 02:52

**Comment by Akram89** [comment]
выполнено
