### ISSUE TITLE
Переделать pawnshop/views.py в пакет

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#20]
**Что нужно сделать:**
Переделать `views.py` в приложении `pawnshop` в пакет `views`
**Как это сделать:**
1. Создать папку `views` в приложении pawnshop
2. Добавить в папку файл `__init__.py`
3. Добавить `.py` файл под каждую сущность
4. Удалить `views.py`

**Зачем это нужно:**
Для масштабируемости и удобство при написании кода

**Критерии приемки:**
В приложении должна появиться папка `views`
**Планируемое время работы:**
5 минут
**Затраченное время:**
20:19 - 20:25

**Comment by Akram89** [comment]
Выполнено
