### ISSUE TITLE
Создать модель категории предметов залога

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#21]
**Что нужно сделать:**
Создать модель `Category`

**Как это сделать:**
1. Создать модель `Category` с полем `pk`, `name`

**Зачем это нужно:**
Для возможности хранения категорий предметов залога

**Критерии приемки:**
В `models.py` приложения `pawnshop` должна появиться модель `Category`

**Планируемое время работы:**
5 минут
**Затраченное время:**
20:40 - 20:44

**Comment by Akram89** [comment]
Выполнено
