### ISSUE TITLE
Создать модель подкатегории предметов залога

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#22]
**Что нужно сделать:**
Создать модель `Subcategory`

**Как это сделать:**
1. Создать модель `Subcategory` с полем `pk`, `name`, внешний ключ на `Category`, внешний ключ на себя

**Зачем это нужно:**
Для возможности хранения подкатегорий предметов залога

**Критерии приемки:**
В `models.py` приложения `pawnshop` должна появиться модель `Subcategory`

**Планируемое время работы:**
10 минут

**Затраченное время:**
21:08 - 21:15

**Comment by Akram89** [comment]
выполнено
