### ISSUE TITLE
Добавить модель PledgeItem

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#26]
**Что нужно сделать:**
Добавить модель PledgeItem

**Как это сделать:**
1. Subcategory
2. name
3. price
4. description
5. note
6. image

**Зачем это нужно:**
Для хранения в базе данных предметов залога

**Критерии приемки:**
Можно в админке создать предмет залога

**Планируемое время работы:**
10 минут

**Затраченное время:**
16:30 - 16:42

**Comment by Akram89** [comment]
выполнено
