### ISSUE TITLE
Добавить флаг модели User

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#28]
**Что нужно сделать:**
Добавить флаг `initial_password_changed_at(datetime)` в модель User

**Как это сделать:**
1. Добавить флаг `initial_password_changed_at(datetime)` в модель User с `auto_now_add=True`

**Зачем это нужно:**
Для понимания, менял ли пользователь пароль, который установил админ

**Критерии приемки:**
У пользователя должно появиться поле, при создании пользователя поле пустое, при смене пароля должно появиться отметка времени, когда пароль был изменен

**Планируемое время работы:**
30 минут

**Затраченное время:**
17:40 - 18:03

**Comment by Akram89** [comment]
выполнено
