### ISSUE TITLE
Добавить на страницу добавления предмета залога выбор подкатегорий

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#29]
**Что нужно сделать:**
В форме поля подкатегорий должны динимически появляться при выборе родительских категорий/подкатегорий

**Как это сделать:**
1. Добавить `SubcategoryDetailAjaxView,` который возвращает подкатегории выбранной категории/подкатегории
2. Добавить Ajax запросы при выборе категории/подкатегории

**Зачем это нужно:**
Чтобы уточнить, к какой подкатегории относится предмет залога

**Критерии приемки:**
При выборе категории, снизу должна появиться select подкатегорий, если у этой категории есть подкатегории

**Планируемое время работы:**
1 час

**Затраченное время:**
11:30 - 01:55

**Comment by Akram89** [comment]
выполнено
