### ISSUE TITLE
Создание страницы личный кабинет админа 

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#31]
**Что нужно сделать:**
Добавить страницу личного кабинета администратора

**Как это сделать:**
1. В `accounts/templates/user` добавить страницы `detail.html`
2. В accounts/views.py добавить метод `UserDetailView.` 
3. Добавить `UserDetailView` в `accounts/views.py:`
 Список пользователей отображает: `pk,` `first_name/middle_name/last_name,` `email,` `user_type,` `is_active.` 
4. Добавить кнопку 'Добавить сотрудника' на странице

**Зачем это нужно:**
Супер админ может посмотреть список пользователей, добавить новых.
 
**Критерии приемки:**

**Планируемое время работы:** 
3  часа

**Затраченное время:**
1о часов включает (часы потраченные на тикет №48)

**Comment by qwanysh** [comment]
Требует доработки. Доработка в тикете #40

**Comment by qwanysh** [comment]
Тикет выполнен неверно. Нужно исправить модель User. Невозможно создать пользователя через админку

**Comment by qwanysh** [comment]
`user/detail.html` не наследует `base.html`

**Comment by qwanysh** [comment]
Реализовано полностью

**Comment by apollo64** [comment]
В графе ФИО: исправить порядок вывода полей.
