### ISSUE TITLE
При вводе неправильного имейла сайт валится

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#32]
**Что нужно сделать**
Отредактировать accounts/views.py/user_login_view

**Как это сделать**
Добавить Try Except блок в выше описанный метод

**Зачем это нужно**
 что бы выдавать сообщение о неправильно введенной информации при неправильно введенном имейле 

**Критерии приемки**
Сайт не должен валиться, а должен выводить на той же странице сообщение о неправильно введенном имейле/пароле.

Срок: 

30мин

Время потрачено: 
12:50-14:11

**Comment by Akram89** [comment]
выполнено
