### ISSUE TITLE
Добавить user_type в модель User

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#33]
Что нужно сделать
Нужно чтобы у пользователей были должности, для дальнейшей работы системы по предоставлению прав пользователям. 

Как это сделать:
В accounts/models/User добавить user_type

Зачем это нужно:
Чтобы суперпользователь мог понимать кто из списка пользователей какую должность занимает. 

Критерии приемки:
В таблице списка пользователей должно быть видно какие обязанности несет каждый зарегистрированный пользователь.
Планируемое время работы:
10 мин

Затраченное время:
18:40-19:00

**Comment by Akram89** [comment]
выполнено
