### ISSUE TITLE
Удалить метки на необязательных полях в форме создания предмета залога

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#34]
**Что нужно сделать:**
Удалить метки на необязательных полях в форме создания предмета залога

**Как это сделать:**
1. Добавить аргумент `required=True` в поля `PledgeItemForm`

**Зачем это нужно:**
Чтобы не вводить в заблуждение клиента

**Критерии приемки:**
В форме клиента звездочки должны показываться только у обязательных полей

**Планируемое время работы:**
5 минут

**Затраченное время:**
17:47 - 17:50

**Comment by Akram89** [comment]
выполнено
