### ISSUE TITLE
Исправить форму создания подтверждающего документа

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#43]
**Что нужно сделать:**
Сейчас при создании подтверждающего документа нужно заполнить все поля(все поля являются обязательными). Нужно исправить `ConfirmDocumentForm` так, чтобы обязательными полями были только: `document_type,` `iin,` `serial_number,` `given_by,` `given_at.`
Нужно в `ConfirmDocumentForm` в необязательные поля добавить аргумент `required=False`

**Зачем это нужно:**
Чтобы можно было оставить пустыми необязательные поля

**Критерии приемки:**
Можно создать подтверждающий документ, не заполняя поля `note`(примечание) и `image`(фотография)

**Планируемое время работы:**
30 минут

**Затраченное время:**
16:00-16:18

**Comment by apollo64** [comment]
Среди полей с  required =True по идее надо внести image. что бы было фото документа .

**Comment by qwanysh** [comment]
Реализовано полностью
