### ISSUE TITLE
Кнопка [Добавить]  в user/detail.html по добавлению пользователей. 

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#48]
Что нужно сделать:
Рабочую кнопку [Добавить];
Как это сделать:
1) Создать  'class UserCreateView' по добавлению нового пользователя;
2) Cоздать форму 'UserForm.py';
3) добавить в urls.py:   'path('/create/', UserCreateView.as_view(), name='user_create')';
4) создать templates / user_create.html

Зачем это нужно:
Что бы админ мог добавлять новых пользователей

Критерии приемки:
Работа 1-3 пунктов

Планируемое время работы:
1 часа

Затраченное время:
18:00 - 20:37

**Comment by qwanysh** [comment]
Реализовано полностью
