### ISSUE TITLE
Поменять порядок вывода имени и отчества в графе "ФИО" 

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#58]
Что нужно сделать:
Сделать так, чтобы в личном кабинете пользователя отчество шло после имени. Сейчас форма выглядит так: Ф О И вместо ФИО

Зачем это нужно:
Для эстетического порядка

Критерии приемки:
В таблице пользователей порядок : фамилия  имя отчество

Планируемое время работы:
10 минут

Затраченное время:
15:15 - 15:28

**Comment by qwanysh** [comment]
Реализовано полностью
