### ISSUE TITLE
Создание версии залогового билета для печати  

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#66]
Что нужно сделать:
Автоматическое создание залогового билета

Зачем это нужно:
 Для завершения процесса оформления кредита. 

Критерии приемки:
После внесения всей информации о пользователе, условиях по кредиту и инфо о залоговом имуществе, формируется залоговый билет с информацией, согласно примеру: 
[Залоговый билет.pdf](https://github.com/glokzs/lombard_crm/files/3676884/default.pdf)
 

Планируемое время работы:
5 часов
Затраченное время:
7 часов

**Comment by Akram89** [comment]
Осталось разобраться с unicode utf-8
