### ISSUE TITLE
Переделать accounts/models.py в пакет

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#7]
**Что нужно сделать:** 
Переделать `accounts/models.py` в пакет `models`

**Как это сделать:** 
1. Создать папку `models`
2. Добавить в папку `__init__.py`
3. Создать файл под каждую модель.
4. Импортировать каждую модель в `__init__.py`
5. Удалить `models.py`

**Зачем это нужно:** 
Для масштабируемости и удобства в работе с кодом

**Критерии приемки:**
В приложении `accounts` должен появиться пакет `models`

**Comment by Akram89** [comment]
Выполнено
