### ISSUE TITLE
Создать тип прав "Аудитор"

### ISSUE THREAD

**Issue by Akram89** [glokzs/lombard_crm#83]
**Что нужно сделать:**
Создать тип прав "Аудитор"

**Зачем это нужно:**
Для разделения прав доступа пользователям

**Критерии приемки:**
При входе на страницу пользователь с правами аудитора должен видеть только список займов. (Без права на создание займа)

**Планируемое время работы:**
3 часа

**Затраченное время:**
4:30 часа

**Comment by apollo64** [comment]
функция реализована, но не получается задавать пароль по SHA256: требуется помощь. Еще не запушил.
