### ISSUE TITLE
Создать модель залогового билета

### ISSUE THREAD

**Issue by Akram89** [glokzs/lombard_crm#87]
Что нужно сделать: Создать модель залогового билета с полями: 
1)UUID
2)OpenDate
3)CloseDate
4)Client_id
5)Loan_Id
6)Branch_Id(пока нет этой модели.)
7)User_Id

Зачем это нужно: Для создания и хранения залогового билета

Критерии приемки: Должен создасться залоговый билет с вышеуказанными полями.

 Планируемое время работы: 1 час 

Затраченное время:
1 час

**Comment by apollo64** [comment]
сделал вместо Close_date  - foreignkey на модель Loan  которая уже имеет всю информацию.

**Comment by apollo64** [comment]
UUID не делал - лучше уточнить у заказчиков, много вариантов исполнения . также добавить ticket_number с foreignkey на pk самой модели.
