### ISSUE TITLE
Добавить файл urls.py в приложение accounts

### ISSUE THREAD

**Issue by qwanysh** [glokzs/lombard_crm#9]
**Что нужно сделать:** 
Добавить `urls.py` в приложение `accounts`

**Как это сделать:**
1. Создать файл `urls.py` в приложении `accounts`
2. Добавить строку `app_name = 'accounts'`
3. Добавить строку `urlpatterns = []`
4. Добавить в `urlpatterns` в `urls.py` корневого приложения строку `path('accounts/', include('accounts.urls', namespace='accounts'))`

**Зачем это нужно:**
Для масштабируемости и удобства при написании кода

**Критерии приемки:**
Роут `accounts/` должен вести на приложение `accounts`

**Comment by Akram89** [comment]
Выполнено
