### ISSUE TITLE
Написать функциональный тест на логирование и регистрацию нового пользователя

### ISSUE THREAD

**Issue by apollo64** [glokzs/lombard_crm#99]
**Что нужно сделать:**
Написать тест через селениум на логирование под админом и регистрацию нового пользователя с правами аудитор

**Зачем это нужно:**
Задание по ESDP

**Критерии приемки:**
Тест проводит процесс регистрации и показывает ошибку если не проводит

**Планируемое время работы:**
2 часа

**Затраченное время:**
40 часов

**Comment by qwanysh** [comment]
Реализовано полностью
